/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface AlertGeoJson {
    "@context"?: WeatherGov.JsonLdContext;
    geometry?: WeatherGov.GeoJsonGeometry;
    id?: string;
    properties?: WeatherGov.Alert;
    type: "Feature";
}
