/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AlertCertainty = "Observed" | "Likely" | "Possible" | "Unlikely" | "Unknown";
export const AlertCertainty = {
    Observed: "Observed",
    Likely: "Likely",
    Possible: "Possible",
    Unlikely: "Unlikely",
    Unknown: "Unknown",
} as const;
