/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface AlertCollectionJsonLd extends WeatherGov.AlertCollection {
    "@context"?: WeatherGov.JsonLdContext;
    "@graph"?: WeatherGov.Alert[];
}
