/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface AlertCollectionGeoJson extends WeatherGov.AlertCollection {
    "@context"?: WeatherGov.JsonLdContext;
    features?: WeatherGov.AlertCollectionGeoJsonFeaturesItem[];
    type: "FeatureCollection";
}
