/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AlertsQueryRequestStatusItem = "actual" | "exercise" | "system" | "test" | "draft";
export const AlertsQueryRequestStatusItem = {
    Actual: "actual",
    Exercise: "exercise",
    System: "system",
    Test: "test",
    Draft: "draft",
} as const;
