/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AlertsQueryRequestMessageTypeItem = "alert" | "update" | "cancel";
export const AlertsQueryRequestMessageTypeItem = {
    Alert: "alert",
    Update: "update",
    Cancel: "cancel",
} as const;
