/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * An alert feed in Atom format
 */
export interface AlertAtomFeed {
    author?: WeatherGov.AlertAtomFeedAuthor;
    entry?: WeatherGov.AlertAtomEntry[];
    generator?: string;
    id?: string;
    title?: string;
    updated?: string;
}
