/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AlertUrgency = "Immediate" | "Expected" | "Future" | "Past" | "Unknown";
export const AlertUrgency = {
    Immediate: "Immediate",
    Expected: "Expected",
    Future: "Future",
    Past: "Past",
    Unknown: "Unknown",
} as const;
