/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AlertsActiveRequestMessageTypeItem = "alert" | "update" | "cancel";
export const AlertsActiveRequestMessageTypeItem = {
    Alert: "alert",
    Update: "update",
    Cancel: "cancel",
} as const;
