/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The code denoting the category of the subject event of the alert message.
 */
export type AlertCategory =
    | "Met"
    | "Geo"
    | "Safety"
    | "Security"
    | "Rescue"
    | "Fire"
    | "Health"
    | "Env"
    | "Transport"
    | "Infra"
    | "CBRNE"
    | "Other";
export const AlertCategory = {
    Met: "Met",
    Geo: "Geo",
    Safety: "Safety",
    Security: "Security",
    Rescue: "Rescue",
    Fire: "Fire",
    Health: "Health",
    Env: "Env",
    Transport: "Transport",
    Infra: "Infra",
    Cbrne: "CBRNE",
    Other: "Other",
} as const;
