/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AlertsQueryRequestRegionType = "land" | "marine";
export const AlertsQueryRequestRegionType = {
    Land: "land",
    Marine: "marine",
} as const;
