/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface AlertReferencesItem {
    /** An API link to the prior alert. */
    "@id"?: string;
    identifier?: WeatherGov.AlertId;
    /** The sender of the prior alert. */
    sender?: string;
    /** The time the prior alert was sent. */
    sent?: string;
}
