/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AlertSeverity = "Extreme" | "Severe" | "Moderate" | "Minor" | "Unknown";
export const AlertSeverity = {
    Extreme: "Extreme",
    Severe: "Severe",
    Moderate: "Moderate",
    Minor: "Minor",
    Unknown: "Unknown",
} as const;
