/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * State/territory codes and marine area codes
 */
export type AreaCode = WeatherGov.StateTerritoryCode | WeatherGov.MarineAreaCode;
