/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface CenterWeatherAdvisory {
    cwsu?: WeatherGov.NwsCenterWeatherServiceUnitId;
    end?: string;
    id?: string;
    issueTime?: string;
    observedProperty?: string;
    sequence?: number;
    start?: string;
    text?: string;
}
