/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface GeoJsonGeometryMultiLineString {
    bbox?: WeatherGov.GeoJsonBoundingBox;
    coordinates: WeatherGov.GeoJsonLineString[];
}
