/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * A GeoJSON polygon. Please refer to IETF RFC 7946 for information on the GeoJSON format.
 */
export type GeoJsonPolygon = WeatherGov.GeoJsonCoordinate[][];
