/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * A GeoJSON geometry object. Please refer to IETF RFC 7946 for information on the GeoJSON format.
 */
export type GeoJsonGeometry =
    | WeatherGov.GeoJsonGeometry.LineString
    | WeatherGov.GeoJsonGeometry.MultiLineString
    | WeatherGov.GeoJsonGeometry.MultiPoint
    | WeatherGov.GeoJsonGeometry.MultiPolygon
    | WeatherGov.GeoJsonGeometry.Point
    | WeatherGov.GeoJsonGeometry.Polygon;

export namespace GeoJsonGeometry {
    export interface LineString extends WeatherGov.GeoJsonGeometryLineString {
        type: "LineString";
    }

    export interface MultiLineString extends WeatherGov.GeoJsonGeometryMultiLineString {
        type: "MultiLineString";
    }

    export interface MultiPoint extends WeatherGov.GeoJsonGeometryMultiPoint {
        type: "MultiPoint";
    }

    export interface MultiPolygon extends WeatherGov.GeoJsonGeometryMultiPolygon {
        type: "MultiPolygon";
    }

    export interface Point extends WeatherGov.GeoJsonGeometryPoint {
        type: "Point";
    }

    export interface Polygon extends WeatherGov.GeoJsonGeometryPolygon {
        type: "Polygon";
    }
}
