/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A GeoJSON coordinate. Please refer to IETF RFC 7946 for information on the GeoJSON format.
 */
export type GeoJsonCoordinate = number[];
