/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface GlossaryResponse {
    "@context"?: WeatherGov.JsonLdContext;
    /** A list of glossary terms */
    glossary?: WeatherGov.GlossaryResponseGlossaryItem[];
}
