/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * A value object representing expected weather phenomena.
 */
export interface GridpointWeatherValuesItemValueItem {
    attributes: WeatherGov.GridpointWeatherValuesItemValueItemAttributesItem[];
    coverage?: WeatherGov.GridpointWeatherValuesItemValueItemCoverage;
    intensity?: WeatherGov.GridpointWeatherValuesItemValueItemIntensity;
    visibility: WeatherGov.QuantitativeValue;
    weather?: WeatherGov.GridpointWeatherValuesItemValueItemWeather;
}
