/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * High/low temperature for the period, depending on whether the period is day or night.
 * This property as an integer value is deprecated. Future versions will express this value as a quantitative value object. To make use of the future standard format now, set the "forecast_temperature_qv" feature flag on the request.
 */
export type GridpointForecastPeriodTemperature = WeatherGov.QuantitativeValue | number;
