/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface GridpointWeatherValuesItem {
    validTime: WeatherGov.Iso8601Interval;
    value: WeatherGov.GridpointWeatherValuesItemValueItem[];
}
