/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The prevailing direction of the wind for the period, using a 16-point compass.
 */
export type GridpointForecastPeriodWindDirection =
    | "N"
    | "NNE"
    | "NE"
    | "ENE"
    | "E"
    | "ESE"
    | "SE"
    | "SSE"
    | "S"
    | "SSW"
    | "SW"
    | "WSW"
    | "W"
    | "WNW"
    | "NW"
    | "NNW";
export const GridpointForecastPeriodWindDirection = {
    N: "N",
    Nne: "NNE",
    Ne: "NE",
    Ene: "ENE",
    E: "E",
    Ese: "ESE",
    Se: "SE",
    Sse: "SSE",
    S: "S",
    Ssw: "SSW",
    Sw: "SW",
    Wsw: "WSW",
    W: "W",
    Wnw: "WNW",
    Nw: "NW",
    Nnw: "NNW",
} as const;
