/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GridpointWeatherValuesItemValueItemCoverage =
    | "areas"
    | "brief"
    | "chance"
    | "definite"
    | "few"
    | "frequent"
    | "intermittent"
    | "isolated"
    | "likely"
    | "numerous"
    | "occasional"
    | "patchy"
    | "periods"
    | "scattered"
    | "slight_chance"
    | "widespread";
export const GridpointWeatherValuesItemValueItemCoverage = {
    Areas: "areas",
    Brief: "brief",
    Chance: "chance",
    Definite: "definite",
    Few: "few",
    Frequent: "frequent",
    Intermittent: "intermittent",
    Isolated: "isolated",
    Likely: "likely",
    Numerous: "numerous",
    Occasional: "occasional",
    Patchy: "patchy",
    Periods: "periods",
    Scattered: "scattered",
    SlightChance: "slight_chance",
    Widespread: "widespread",
} as const;
