/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GridpointForecastHourlyRequestFeatureFlagsItem = "forecast_temperature_qv" | "forecast_wind_speed_qv";
export const GridpointForecastHourlyRequestFeatureFlagsItem = {
    ForecastTemperatureQv: "forecast_temperature_qv",
    ForecastWindSpeedQv: "forecast_wind_speed_qv",
} as const;
