/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface GridpointQuantitativeValueLayerValuesItem {
    validTime: WeatherGov.Iso8601Interval;
    value?: number;
}
