/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * A gridpoint layer consisting of quantitative values (numeric values with associated units of measure).
 */
export interface GridpointQuantitativeValueLayer {
    uom?: WeatherGov.UnitOfMeasure;
    values: WeatherGov.GridpointQuantitativeValueLayerValuesItem[];
}
