/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GridpointWeatherValuesItemValueItemAttributesItem =
    | "damaging_wind"
    | "dry_thunderstorms"
    | "flooding"
    | "gusty_wind"
    | "heavy_rain"
    | "large_hail"
    | "small_hail"
    | "tornadoes";
export const GridpointWeatherValuesItemValueItemAttributesItem = {
    DamagingWind: "damaging_wind",
    DryThunderstorms: "dry_thunderstorms",
    Flooding: "flooding",
    GustyWind: "gusty_wind",
    HeavyRain: "heavy_rain",
    LargeHail: "large_hail",
    SmallHail: "small_hail",
    Tornadoes: "tornadoes",
} as const;
