/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GridpointWeatherValuesItemValueItemIntensity = "very_light" | "light" | "moderate" | "heavy";
export const GridpointWeatherValuesItemValueItemIntensity = {
    VeryLight: "very_light",
    Light: "light",
    Moderate: "moderate",
    Heavy: "heavy",
} as const;
