/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GridpointWeatherValuesItemValueItemWeather =
    | "blowing_dust"
    | "blowing_sand"
    | "blowing_snow"
    | "drizzle"
    | "fog"
    | "freezing_fog"
    | "freezing_drizzle"
    | "freezing_rain"
    | "freezing_spray"
    | "frost"
    | "hail"
    | "haze"
    | "ice_crystals"
    | "ice_fog"
    | "rain"
    | "rain_showers"
    | "sleet"
    | "smoke"
    | "snow"
    | "snow_showers"
    | "thunderstorms"
    | "volcanic_ash"
    | "water_spouts";
export const GridpointWeatherValuesItemValueItemWeather = {
    BlowingDust: "blowing_dust",
    BlowingSand: "blowing_sand",
    BlowingSnow: "blowing_snow",
    Drizzle: "drizzle",
    Fog: "fog",
    FreezingFog: "freezing_fog",
    FreezingDrizzle: "freezing_drizzle",
    FreezingRain: "freezing_rain",
    FreezingSpray: "freezing_spray",
    Frost: "frost",
    Hail: "hail",
    Haze: "haze",
    IceCrystals: "ice_crystals",
    IceFog: "ice_fog",
    Rain: "rain",
    RainShowers: "rain_showers",
    Sleet: "sleet",
    Smoke: "smoke",
    Snow: "snow",
    SnowShowers: "snow_showers",
    Thunderstorms: "thunderstorms",
    VolcanicAsh: "volcanic_ash",
    WaterSpouts: "water_spouts",
} as const;
