/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Denotes the units used in the textual portions of the forecast.
 */
export type GridpointForecastUnits = "us" | "si";
export const GridpointForecastUnits = {
    Us: "us",
    Si: "si",
} as const;
