/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * A multi-day forecast for a 2.5km grid square.
 */
export interface GridpointForecast {
    "@context"?: WeatherGov.JsonLdContext;
    elevation?: WeatherGov.QuantitativeValue;
    /** The internal generator class used to create the forecast text (used for NWS debugging). */
    forecastGenerator?: string;
    /** The time this forecast data was generated. */
    generatedAt?: string;
    geometry?: WeatherGov.GeometryString | undefined;
    /** An array of forecast periods. */
    periods?: WeatherGov.GridpointForecastPeriod[];
    units?: WeatherGov.GridpointForecastUnits;
    /** The last update time of the data this forecast was generated from. */
    updateTime?: string;
    validTimes?: WeatherGov.Iso8601Interval;
}
