/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface IconsSummaryResponse {
    "@context"?: WeatherGov.JsonLdContext;
    icons: Record<string, WeatherGov.IconsSummaryResponseIconsValue>;
}
