/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IconsRequestSize = "small" | "medium" | "large";
export const IconsRequestSize = {
    Small: "small",
    Medium: "medium",
    Large: "large",
} as const;
