/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Land region code. These correspond to the six NWS regional headquarters:
 * * AR: Alaska Region
 * * CR: Central Region
 * * ER: Eastern Region
 * * PR: Pacific Region
 * * SR: Southern Region
 * * WR: Western Region
 */
export type LandRegionCode = "AR" | "CR" | "ER" | "PR" | "SR" | "WR";
export const LandRegionCode = {
    Ar: "AR",
    Cr: "CR",
    Er: "ER",
    Pr: "PR",
    Sr: "SR",
    Wr: "WR",
} as const;
