/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MetarPhenomenonWeather =
    | "fog_mist"
    | "dust_storm"
    | "dust"
    | "drizzle"
    | "funnel_cloud"
    | "fog"
    | "smoke"
    | "hail"
    | "snow_pellets"
    | "haze"
    | "ice_crystals"
    | "ice_pellets"
    | "dust_whirls"
    | "spray"
    | "rain"
    | "sand"
    | "snow_grains"
    | "snow"
    | "squalls"
    | "sand_storm"
    | "thunderstorms"
    | "unknown"
    | "volcanic_ash";
export const MetarPhenomenonWeather = {
    FogMist: "fog_mist",
    DustStorm: "dust_storm",
    Dust: "dust",
    Drizzle: "drizzle",
    FunnelCloud: "funnel_cloud",
    Fog: "fog",
    Smoke: "smoke",
    Hail: "hail",
    SnowPellets: "snow_pellets",
    Haze: "haze",
    IceCrystals: "ice_crystals",
    IcePellets: "ice_pellets",
    DustWhirls: "dust_whirls",
    Spray: "spray",
    Rain: "rain",
    Sand: "sand",
    SnowGrains: "snow_grains",
    Snow: "snow",
    Squalls: "squalls",
    SandStorm: "sand_storm",
    Thunderstorms: "thunderstorms",
    Unknown: "unknown",
    VolcanicAsh: "volcanic_ash",
} as const;
