/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MetarPhenomenonIntensity = "light" | "heavy";
export const MetarPhenomenonIntensity = {
    Light: "light",
    Heavy: "heavy",
} as const;
