/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * An object representing a decoded METAR phenomenon string.
 */
export interface MetarPhenomenon {
    intensity?: WeatherGov.MetarPhenomenonIntensity;
    inVicinity?: boolean;
    modifier?: WeatherGov.MetarPhenomenonModifier;
    rawString: string;
    weather: WeatherGov.MetarPhenomenonWeather;
}
