/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Three-letter identifier for a Center Weather Service Unit (CWSU).
 */
export type NwsCenterWeatherServiceUnitId =
    | "ZAB"
    | "ZAN"
    | "ZAU"
    | "ZBW"
    | "ZDC"
    | "ZDV"
    | "ZFA"
    | "ZFW"
    | "ZHU"
    | "ZID"
    | "ZJX"
    | "ZKC"
    | "ZLA"
    | "ZLC"
    | "ZMA"
    | "ZME"
    | "ZMP"
    | "ZNY"
    | "ZOA"
    | "ZOB"
    | "ZSE"
    | "ZTL";
export const NwsCenterWeatherServiceUnitId = {
    Zab: "ZAB",
    Zan: "ZAN",
    Zau: "ZAU",
    Zbw: "ZBW",
    Zdc: "ZDC",
    Zdv: "ZDV",
    Zfa: "ZFA",
    Zfw: "ZFW",
    Zhu: "ZHU",
    Zid: "ZID",
    Zjx: "ZJX",
    Zkc: "ZKC",
    Zla: "ZLA",
    Zlc: "ZLC",
    Zma: "ZMA",
    Zme: "ZME",
    Zmp: "ZMP",
    Zny: "ZNY",
    Zoa: "ZOA",
    Zob: "ZOB",
    Zse: "ZSE",
    Ztl: "ZTL",
} as const;
