/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export type NwsOfficeId = WeatherGov.NwsForecastOfficeId | WeatherGov.NwsRegionalHqId | WeatherGov.NwsNationalHqId;
