/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Three-letter identifier for a NWS Regional HQ.
 */
export type NwsRegionalHqId = "ARH" | "CRH" | "ERH" | "PRH" | "SRH" | "WRH";
export const NwsRegionalHqId = {
    Arh: "ARH",
    Crh: "CRH",
    Erh: "ERH",
    Prh: "PRH",
    Srh: "SRH",
    Wrh: "WRH",
} as const;
