/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * UGC identifier for a NWS forecast zone or county.
 * The first two letters will correspond to either a state code or marine area code (see #/components/schemas/StateTerritoryCode and #/components/schemas/MarineAreaCode for lists of valid letter combinations).
 * The third letter will be Z for public/fire zone or C for county.
 */
export type NwsZoneId = string;
