/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NwsZoneType = "land" | "marine" | "forecast" | "public" | "coastal" | "offshore" | "fire" | "county";
export const NwsZoneType = {
    Land: "land",
    Marine: "marine",
    Forecast: "forecast",
    Public: "public",
    Coastal: "coastal",
    Offshore: "offshore",
    Fire: "fire",
    County: "county",
} as const;
