/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface ObservationCloudLayersItem {
    amount: WeatherGov.MetarSkyCoverage;
    base: WeatherGov.QuantitativeValue;
}
