/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface ObservationStationCollectionJsonLd {
    "@context"?: WeatherGov.JsonLdContext;
    "@graph"?: WeatherGov.ObservationStation[];
    observationStations?: string[];
    pagination?: WeatherGov.PaginationInfo;
}
