/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface ObservationStationCollectionGeoJson {
    "@context"?: WeatherGov.JsonLdContext;
    features?: WeatherGov.ObservationStationCollectionGeoJsonFeaturesItem[];
    observationStations?: string[];
    pagination?: WeatherGov.PaginationInfo;
    type: "FeatureCollection";
}
