/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface Observation {
    "@context"?: WeatherGov.JsonLdContext;
    "@id"?: string;
    "@type"?: "wx:ObservationStation";
    barometricPressure?: WeatherGov.QuantitativeValue;
    cloudLayers?: WeatherGov.ObservationCloudLayersItem[];
    dewpoint?: WeatherGov.QuantitativeValue;
    elevation?: WeatherGov.QuantitativeValue;
    geometry?: WeatherGov.GeometryString | undefined;
    heatIndex?: WeatherGov.QuantitativeValue;
    icon?: string;
    maxTemperatureLast24Hours?: WeatherGov.QuantitativeValue;
    minTemperatureLast24Hours?: WeatherGov.QuantitativeValue;
    precipitationLast3Hours?: WeatherGov.QuantitativeValue;
    precipitationLast6Hours?: WeatherGov.QuantitativeValue;
    precipitationLastHour?: WeatherGov.QuantitativeValue;
    presentWeather?: WeatherGov.MetarPhenomenon[];
    rawMessage?: string;
    relativeHumidity?: WeatherGov.QuantitativeValue;
    seaLevelPressure?: WeatherGov.QuantitativeValue;
    station?: string;
    temperature?: WeatherGov.QuantitativeValue;
    textDescription?: string;
    timestamp?: string;
    visibility?: WeatherGov.QuantitativeValue;
    windChill?: WeatherGov.QuantitativeValue;
    windDirection?: WeatherGov.QuantitativeValue;
    windGust?: WeatherGov.QuantitativeValue;
    windSpeed?: WeatherGov.QuantitativeValue;
}
