/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface ObservationCollectionGeoJson {
    "@context"?: WeatherGov.JsonLdContext;
    features?: WeatherGov.ObservationCollectionGeoJsonFeaturesItem[];
    type: "FeatureCollection";
}
