/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface ObservationStation {
    "@context"?: WeatherGov.JsonLdContext;
    "@id"?: string;
    "@type"?: "wx:ObservationStation";
    /** A link to the NWS county zone containing this station. */
    county?: string;
    elevation?: WeatherGov.QuantitativeValue;
    /** A link to the NWS fire weather forecast zone containing this station. */
    fireWeatherZone?: string;
    /** A link to the NWS public forecast zone containing this station. */
    forecast?: string;
    geometry?: WeatherGov.GeometryString | undefined;
    name?: string;
    stationIdentifier?: string;
    timeZone?: string;
}
