/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface Office {
    "@context"?: WeatherGov.JsonLdContext;
    "@id"?: string;
    "@type"?: "GovernmentOrganization";
    address?: WeatherGov.OfficeAddress;
    approvedObservationStations?: string[];
    email?: string;
    faxNumber?: string;
    id?: string;
    name?: string;
    nwsRegion?: string;
    parentOrganization?: string;
    responsibleCounties?: string[];
    responsibleFireZones?: string[];
    responsibleForecastZones?: string[];
    sameAs?: string;
    telephone?: string;
}
