/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Links for retrieving more data from paged data sets
 */
export interface PaginationInfo {
    /** A link to the next page of records */
    next: string;
}
