/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface Point {
    "@context"?: WeatherGov.JsonLdContext;
    "@id"?: string;
    "@type"?: "wx:Point";
    county?: string;
    cwa?: WeatherGov.NwsForecastOfficeId;
    fireWeatherZone?: string;
    forecast?: string;
    forecastGridData?: string;
    forecastHourly?: string;
    forecastOffice?: string;
    forecastZone?: string;
    geometry?: WeatherGov.GeometryString | undefined;
    gridId?: WeatherGov.NwsForecastOfficeId;
    gridX?: number;
    gridY?: number;
    observationStations?: string;
    radarStation?: string;
    relativeLocation?: WeatherGov.PointRelativeLocation;
    timeZone?: string;
}
