/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * For values in observation records, the quality control flag from the MADIS system. The definitions of these flags can be found at https://madis.ncep.noaa.gov/madis_sfc_qc_notes.shtml
 */
export type QuantitativeValueQualityControl = "Z" | "C" | "S" | "V" | "X" | "Q" | "G" | "B" | "T";
export const QuantitativeValueQualityControl = {
    Z: "Z",
    C: "C",
    S: "S",
    V: "V",
    X: "X",
    Q: "Q",
    G: "G",
    B: "B",
    T: "T",
} as const;
