/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

/**
 * A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue
 */
export interface QuantitativeValue {
    /** The maximum value of a range of measured values */
    maxValue?: number;
    /** The minimum value of a range of measured values */
    minValue?: number;
    /** For values in observation records, the quality control flag from the MADIS system. The definitions of these flags can be found at https://madis.ncep.noaa.gov/madis_sfc_qc_notes.shtml */
    qualityControl?: WeatherGov.QuantitativeValueQualityControl;
    unitCode?: WeatherGov.UnitOfMeasure;
    /** A measured value */
    value?: number;
}
