/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface RelativeLocation {
    bearing?: WeatherGov.QuantitativeValue;
    city?: string;
    distance?: WeatherGov.QuantitativeValue;
    state?: string;
}
