/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface RelativeLocationJsonLd extends WeatherGov.RelativeLocation {
    geometry?: WeatherGov.GeometryString | undefined;
}
