/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SatelliteThumbnailsRequestArea = "a" | "e" | "g" | "h" | "p" | "s" | "w";
export const SatelliteThumbnailsRequestArea = {
    A: "a",
    E: "e",
    G: "g",
    H: "h",
    P: "p",
    S: "s",
    W: "w",
} as const;
