/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface Sigmet {
    atsu?: WeatherGov.AtsuIdentifier;
    end?: string;
    fir?: string;
    id?: string;
    issueTime?: string;
    phenomenon?: string;
    sequence?: string;
    start?: string;
}
