/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface TextProductLocationCollection {
    "@context"?: WeatherGov.JsonLdContext;
    locations?: Record<string, string | undefined>;
}
