/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface TextProductTypeCollection {
    "@context"?: WeatherGov.JsonLdContext;
    "@graph"?: WeatherGov.TextProductTypeCollectionGraphItem[];
}
