/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface TextProduct {
    "@context"?: WeatherGov.JsonLdContext;
    "@id"?: string;
    id?: string;
    issuanceTime?: string;
    issuingOffice?: string;
    productCode?: string;
    productName?: string;
    productText?: string;
    wmoCollectiveId?: string;
}
