/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../index";

export interface Zone {
    "@context"?: WeatherGov.JsonLdContext;
    "@id"?: string;
    "@type"?: "wx:Zone";
    awipsLocationIdentifier?: string;
    cwa?: WeatherGov.NwsForecastOfficeId[];
    effectiveDate?: string;
    expirationDate?: string;
    forecastOffice?: string;
    forecastOffices?: string[];
    geometry?: WeatherGov.GeometryString | undefined;
    gridIdentifier?: string;
    id?: WeatherGov.NwsZoneId;
    name?: string;
    observationStations?: string[];
    radarStation?: string;
    state?: WeatherGov.ZoneState;
    timeZone?: string[];
    type?: WeatherGov.NwsZoneType;
}
