"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertsQueryRequestMessageTypeItem = void 0;
exports.AlertsQueryRequestMessageTypeItem = {
    Alert: "alert",
    Update: "update",
    Cancel: "cancel",
};
