/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AlertsQueryRequestMessageTypeItem = "alert" | "update" | "cancel";
export declare const AlertsQueryRequestMessageTypeItem: {
    readonly Alert: "alert";
    readonly Update: "update";
    readonly Cancel: "cancel";
};
