/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface AlertCollectionGeoJson extends AbvthecityWeatherGov.AlertCollection {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    features?: AbvthecityWeatherGov.AlertCollectionGeoJsonFeaturesItem[];
    type: "FeatureCollection";
}
