"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertsActiveRequestStatusItem = void 0;
exports.AlertsActiveRequestStatusItem = {
    Actual: "actual",
    Exercise: "exercise",
    System: "system",
    Test: "test",
    Draft: "draft",
};
