/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AlertMessageType = "Alert" | "Update" | "Cancel" | "Ack" | "Error";
export declare const AlertMessageType: {
    readonly Alert: "Alert";
    readonly Update: "Update";
    readonly Cancel: "Cancel";
    readonly Ack: "Ack";
    readonly Error: "Error";
};
