/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AlertSeverity = "Extreme" | "Severe" | "Moderate" | "Minor" | "Unknown";
export declare const AlertSeverity: {
    readonly Extreme: "Extreme";
    readonly Severe: "Severe";
    readonly Moderate: "Moderate";
    readonly Minor: "Minor";
    readonly Unknown: "Unknown";
};
