/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AlertUrgency = "Immediate" | "Expected" | "Future" | "Past" | "Unknown";
export declare const AlertUrgency: {
    readonly Immediate: "Immediate";
    readonly Expected: "Expected";
    readonly Future: "Future";
    readonly Past: "Past";
    readonly Unknown: "Unknown";
};
