"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertMessageType = void 0;
exports.AlertMessageType = {
    Alert: "Alert",
    Update: "Update",
    Cancel: "Cancel",
    Ack: "Ack",
    Error: "Error",
};
