/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AlertsActiveRequestStatusItem = "actual" | "exercise" | "system" | "test" | "draft";
export declare const AlertsActiveRequestStatusItem: {
    readonly Actual: "actual";
    readonly Exercise: "exercise";
    readonly System: "system";
    readonly Test: "test";
    readonly Draft: "draft";
};
