/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The code denoting the type of action recommended for the target audience.
 * This corresponds to responseType in the CAP specification.
 */
export type AlertResponse = "Shelter" | "Evacuate" | "Prepare" | "Execute" | "Avoid" | "Monitor" | "Assess" | "AllClear" | "None";
export declare const AlertResponse: {
    readonly Shelter: "Shelter";
    readonly Evacuate: "Evacuate";
    readonly Prepare: "Prepare";
    readonly Execute: "Execute";
    readonly Avoid: "Avoid";
    readonly Monitor: "Monitor";
    readonly Assess: "Assess";
    readonly AllClear: "AllClear";
    readonly None: "None";
};
