"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertUrgency = void 0;
exports.AlertUrgency = {
    Immediate: "Immediate",
    Expected: "Expected",
    Future: "Future",
    Past: "Past",
    Unknown: "Unknown",
};
