"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertsQueryRequestRegionType = void 0;
exports.AlertsQueryRequestRegionType = {
    Land: "land",
    Marine: "marine",
};
