"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertCertainty = void 0;
exports.AlertCertainty = {
    Observed: "Observed",
    Likely: "Likely",
    Possible: "Possible",
    Unlikely: "Unlikely",
    Unknown: "Unknown",
};
