/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AlertCertainty = "Observed" | "Likely" | "Possible" | "Unlikely" | "Unknown";
export declare const AlertCertainty: {
    readonly Observed: "Observed";
    readonly Likely: "Likely";
    readonly Possible: "Possible";
    readonly Unlikely: "Unlikely";
    readonly Unknown: "Unknown";
};
