"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertStatus = void 0;
exports.AlertStatus = {
    Actual: "Actual",
    Exercise: "Exercise",
    System: "System",
    Test: "Test",
    Draft: "Draft",
};
