"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertCategory = void 0;
exports.AlertCategory = {
    Met: "Met",
    Geo: "Geo",
    Safety: "Safety",
    Security: "Security",
    Rescue: "Rescue",
    Fire: "Fire",
    Health: "Health",
    Env: "Env",
    Transport: "Transport",
    Infra: "Infra",
    Cbrne: "CBRNE",
    Other: "Other",
};
