"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertResponse = void 0;
exports.AlertResponse = {
    Shelter: "Shelter",
    Evacuate: "Evacuate",
    Prepare: "Prepare",
    Execute: "Execute",
    Avoid: "Avoid",
    Monitor: "Monitor",
    Assess: "Assess",
    AllClear: "AllClear",
    None: "None",
};
