"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AlertSeverity = void 0;
exports.AlertSeverity = {
    Extreme: "Extreme",
    Severe: "Severe",
    Moderate: "Moderate",
    Minor: "Minor",
    Unknown: "Unknown",
};
