/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface CenterWeatherAdvisoryGeoJson {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    geometry?: AbvthecityWeatherGov.GeoJsonGeometry;
    id?: string;
    properties?: AbvthecityWeatherGov.CenterWeatherAdvisory;
    type: "Feature";
}
