/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface GeoJsonGeometryMultiPoint {
    bbox?: AbvthecityWeatherGov.GeoJsonBoundingBox;
    coordinates: AbvthecityWeatherGov.GeoJsonCoordinate[];
}
