/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * A GeoJSON line string. Please refer to IETF RFC 7946 for information on the GeoJSON format.
 */
export type GeoJsonLineString = AbvthecityWeatherGov.GeoJsonCoordinate[];
