/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * A GeoJSON feature. Please refer to IETF RFC 7946 for information on the GeoJSON format.
 */
export interface GeoJsonFeature {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    geometry?: AbvthecityWeatherGov.GeoJsonGeometry;
    id?: string;
    properties: Record<string, unknown>;
    type: "Feature";
}
