/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface GeoJsonGeometryLineString {
    bbox?: AbvthecityWeatherGov.GeoJsonBoundingBox;
    coordinates: AbvthecityWeatherGov.GeoJsonLineString;
}
