/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface GeoJsonGeometryPolygon {
    bbox?: AbvthecityWeatherGov.GeoJsonBoundingBox;
    coordinates: AbvthecityWeatherGov.GeoJsonPolygon;
}
