/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GlossaryResponseGlossaryItem {
    /** A definition for the term */
    definition?: string;
    /** The term being defined */
    term?: string;
}
