/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface GlossaryResponse {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    /** A list of glossary terms */
    glossary?: AbvthecityWeatherGov.GlossaryResponseGlossaryItem[];
}
