"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridpointWeatherValuesItemValueItemCoverage = void 0;
exports.GridpointWeatherValuesItemValueItemCoverage = {
    Areas: "areas",
    Brief: "brief",
    Chance: "chance",
    Definite: "definite",
    Few: "few",
    Frequent: "frequent",
    Intermittent: "intermittent",
    Isolated: "isolated",
    Likely: "likely",
    Numerous: "numerous",
    Occasional: "occasional",
    Patchy: "patchy",
    Periods: "periods",
    Scattered: "scattered",
    SlightChance: "slight_chance",
    Widespread: "widespread",
};
