/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * A value object representing expected weather phenomena.
 */
export interface GridpointWeatherValuesItemValueItem {
    attributes: AbvthecityWeatherGov.GridpointWeatherValuesItemValueItemAttributesItem[];
    coverage?: AbvthecityWeatherGov.GridpointWeatherValuesItemValueItemCoverage;
    intensity?: AbvthecityWeatherGov.GridpointWeatherValuesItemValueItemIntensity;
    visibility: AbvthecityWeatherGov.QuantitativeValue;
    weather?: AbvthecityWeatherGov.GridpointWeatherValuesItemValueItemWeather;
}
