/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type GridpointWeatherValuesItemValueItemIntensity = "very_light" | "light" | "moderate" | "heavy";
export declare const GridpointWeatherValuesItemValueItemIntensity: {
    readonly VeryLight: "very_light";
    readonly Light: "light";
    readonly Moderate: "moderate";
    readonly Heavy: "heavy";
};
