/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The unit of the temperature value (Fahrenheit or Celsius).
 * This property is deprecated. Future versions will indicate the unit within the quantitative value object for the temperature property. To make use of the future standard format now, set the "forecast_temperature_qv" feature flag on the request.
 */
export type GridpointForecastPeriodTemperatureUnit = "F" | "C";
export declare const GridpointForecastPeriodTemperatureUnit: {
    readonly F: "F";
    readonly C: "C";
};
