"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridpointWeatherValuesItemValueItemWeather = void 0;
exports.GridpointWeatherValuesItemValueItemWeather = {
    BlowingDust: "blowing_dust",
    BlowingSand: "blowing_sand",
    BlowingSnow: "blowing_snow",
    Drizzle: "drizzle",
    Fog: "fog",
    FreezingFog: "freezing_fog",
    FreezingDrizzle: "freezing_drizzle",
    FreezingRain: "freezing_rain",
    FreezingSpray: "freezing_spray",
    Frost: "frost",
    Hail: "hail",
    Haze: "haze",
    IceCrystals: "ice_crystals",
    IceFog: "ice_fog",
    Rain: "rain",
    RainShowers: "rain_showers",
    Sleet: "sleet",
    Smoke: "smoke",
    Snow: "snow",
    SnowShowers: "snow_showers",
    Thunderstorms: "thunderstorms",
    VolcanicAsh: "volcanic_ash",
    WaterSpouts: "water_spouts",
};
