"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridpointWeatherValuesItemValueItemIntensity = void 0;
exports.GridpointWeatherValuesItemValueItemIntensity = {
    VeryLight: "very_light",
    Light: "light",
    Moderate: "moderate",
    Heavy: "heavy",
};
