"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridpointForecastPeriodTemperatureTrend = void 0;
exports.GridpointForecastPeriodTemperatureTrend = {
    Rising: "rising",
    Falling: "falling",
};
