"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridpointWeatherValuesItemValueItemAttributesItem = void 0;
exports.GridpointWeatherValuesItemValueItemAttributesItem = {
    DamagingWind: "damaging_wind",
    DryThunderstorms: "dry_thunderstorms",
    Flooding: "flooding",
    GustyWind: "gusty_wind",
    HeavyRain: "heavy_rain",
    LargeHail: "large_hail",
    SmallHail: "small_hail",
    Tornadoes: "tornadoes",
};
