/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * A gridpoint layer consisting of quantitative values (numeric values with associated units of measure).
 */
export interface GridpointQuantitativeValueLayer {
    uom?: AbvthecityWeatherGov.UnitOfMeasure;
    values: AbvthecityWeatherGov.GridpointQuantitativeValueLayerValuesItem[];
}
