"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridpointForecastHourlyRequestFeatureFlagsItem = void 0;
exports.GridpointForecastHourlyRequestFeatureFlagsItem = {
    ForecastTemperatureQv: "forecast_temperature_qv",
    ForecastWindSpeedQv: "forecast_wind_speed_qv",
};
