"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridpointForecastPeriodWindDirection = void 0;
exports.GridpointForecastPeriodWindDirection = {
    N: "N",
    Nne: "NNE",
    Ne: "NE",
    Ene: "ENE",
    E: "E",
    Ese: "ESE",
    Se: "SE",
    Sse: "SSE",
    S: "S",
    Ssw: "SSW",
    Sw: "SW",
    Wsw: "WSW",
    W: "W",
    Wnw: "WNW",
    Nw: "NW",
    Nnw: "NNW",
};
