/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * An object containing forecast information for a specific time period (generally 12-hour or 1-hour).
 */
export interface GridpointForecastPeriod {
    /** A detailed textual forecast for the period. */
    detailedForecast?: string;
    dewpoint?: AbvthecityWeatherGov.QuantitativeValue;
    /** The ending time that this forecast period is valid for. */
    endTime?: string;
    /** A link to an icon representing the forecast summary. */
    icon?: string;
    /** Indicates whether this period is daytime or nighttime. */
    isDaytime?: boolean;
    /** A textual identifier for the period. This value will not be present for hourly forecasts. */
    name?: string;
    /** Sequential period number. */
    number?: number;
    probabilityOfPrecipitation?: AbvthecityWeatherGov.QuantitativeValue;
    relativeHumidity?: AbvthecityWeatherGov.QuantitativeValue;
    /** A brief textual forecast summary for the period. */
    shortForecast?: string;
    /** The starting time that this forecast period is valid for. */
    startTime?: string;
    /**
     * High/low temperature for the period, depending on whether the period is day or night.
     * This property as an integer value is deprecated. Future versions will express this value as a quantitative value object. To make use of the future standard format now, set the "forecast_temperature_qv" feature flag on the request.
     */
    temperature?: AbvthecityWeatherGov.GridpointForecastPeriodTemperature;
    /** If not null, indicates a non-diurnal temperature trend for the period (either rising temperature overnight, or falling temperature during the day) */
    temperatureTrend?: AbvthecityWeatherGov.GridpointForecastPeriodTemperatureTrend;
    /**
     * The unit of the temperature value (Fahrenheit or Celsius).
     * This property is deprecated. Future versions will indicate the unit within the quantitative value object for the temperature property. To make use of the future standard format now, set the "forecast_temperature_qv" feature flag on the request.
     */
    temperatureUnit?: AbvthecityWeatherGov.GridpointForecastPeriodTemperatureUnit;
    /** The prevailing direction of the wind for the period, using a 16-point compass. */
    windDirection?: AbvthecityWeatherGov.GridpointForecastPeriodWindDirection;
    /**
     * Peak wind gust for the period.
     * This property as an string value is deprecated. Future versions will express this value as a quantitative value object. To make use of the future standard format now, set the "forecast_wind_speed_qv" feature flag on the request.
     */
    windGust?: AbvthecityWeatherGov.GridpointForecastPeriodWindGust;
    /**
     * Wind speed for the period.
     * This property as an string value is deprecated. Future versions will express this value as a quantitative value object. To make use of the future standard format now, set the "forecast_wind_speed_qv" feature flag on the request.
     */
    windSpeed?: AbvthecityWeatherGov.GridpointForecastPeriodWindSpeed;
}
