/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface GridpointWeatherValuesItem {
    validTime: AbvthecityWeatherGov.Iso8601Interval;
    value: AbvthecityWeatherGov.GridpointWeatherValuesItemValueItem[];
}
