/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type GridpointWeatherValuesItemValueItemCoverage = "areas" | "brief" | "chance" | "definite" | "few" | "frequent" | "intermittent" | "isolated" | "likely" | "numerous" | "occasional" | "patchy" | "periods" | "scattered" | "slight_chance" | "widespread";
export declare const GridpointWeatherValuesItemValueItemCoverage: {
    readonly Areas: "areas";
    readonly Brief: "brief";
    readonly Chance: "chance";
    readonly Definite: "definite";
    readonly Few: "few";
    readonly Frequent: "frequent";
    readonly Intermittent: "intermittent";
    readonly Isolated: "isolated";
    readonly Likely: "likely";
    readonly Numerous: "numerous";
    readonly Occasional: "occasional";
    readonly Patchy: "patchy";
    readonly Periods: "periods";
    readonly Scattered: "scattered";
    readonly SlightChance: "slight_chance";
    readonly Widespread: "widespread";
};
