/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type GridpointWeatherValuesItemValueItemWeather = "blowing_dust" | "blowing_sand" | "blowing_snow" | "drizzle" | "fog" | "freezing_fog" | "freezing_drizzle" | "freezing_rain" | "freezing_spray" | "frost" | "hail" | "haze" | "ice_crystals" | "ice_fog" | "rain" | "rain_showers" | "sleet" | "smoke" | "snow" | "snow_showers" | "thunderstorms" | "volcanic_ash" | "water_spouts";
export declare const GridpointWeatherValuesItemValueItemWeather: {
    readonly BlowingDust: "blowing_dust";
    readonly BlowingSand: "blowing_sand";
    readonly BlowingSnow: "blowing_snow";
    readonly Drizzle: "drizzle";
    readonly Fog: "fog";
    readonly FreezingFog: "freezing_fog";
    readonly FreezingDrizzle: "freezing_drizzle";
    readonly FreezingRain: "freezing_rain";
    readonly FreezingSpray: "freezing_spray";
    readonly Frost: "frost";
    readonly Hail: "hail";
    readonly Haze: "haze";
    readonly IceCrystals: "ice_crystals";
    readonly IceFog: "ice_fog";
    readonly Rain: "rain";
    readonly RainShowers: "rain_showers";
    readonly Sleet: "sleet";
    readonly Smoke: "smoke";
    readonly Snow: "snow";
    readonly SnowShowers: "snow_showers";
    readonly Thunderstorms: "thunderstorms";
    readonly VolcanicAsh: "volcanic_ash";
    readonly WaterSpouts: "water_spouts";
};
