/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface IconsSummaryResponse {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    icons: Record<string, AbvthecityWeatherGov.IconsSummaryResponseIconsValue>;
}
