"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IconsRequestSize = void 0;
exports.IconsRequestSize = {
    Small: "small",
    Medium: "medium",
    Large: "large",
};
