"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LandRegionCode = void 0;
exports.LandRegionCode = {
    Ar: "AR",
    Cr: "CR",
    Er: "ER",
    Pr: "PR",
    Sr: "SR",
    Wr: "WR",
};
