"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MarineAreaCode = void 0;
exports.MarineAreaCode = {
    Am: "AM",
    An: "AN",
    Gm: "GM",
    Lc: "LC",
    Le: "LE",
    Lh: "LH",
    Lm: "LM",
    Lo: "LO",
    Ls: "LS",
    Ph: "PH",
    Pk: "PK",
    Pm: "PM",
    Ps: "PS",
    Pz: "PZ",
    Sl: "SL",
};
