/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Marine area code as defined in NWS Directive 10-302:
 *
 * - AM: Western North Atlantic Ocean and along U.S. East Coast south of Currituck Beach Light NC following the coastline into Gulf of Mexico to Ocean Reef FL including the Caribbean
 * - AN: Western North Atlantic Ocean and along U.S. East Coast from Canadian border south to Currituck Beach Light NC
 * - GM: Gulf of Mexico and along the U.S. Gulf Coast from the Mexican border to Ocean Reef FL
 * - LC: Lake St. Clair
 * - LE: Lake Erie
 * - LH: Lake Huron
 * - LM: Lake Michigan
 * - LO: Lake Ontario
 * - LS: Lake Superior
 * - PH: Central Pacific Ocean including Hawaiian waters
 * - PK: North Pacific Ocean near Alaska and along Alaska coastline including the Bering Sea and the Gulf of Alaska
 * - PM: Western Pacific Ocean including Mariana Island waters
 * - PS: South Central Pacific Ocean including American Samoa waters
 * - PZ: Eastern North Pacific Ocean and along U.S. West Coast from Canadian border to Mexican border
 * - SL: St. Lawrence River above St. Regis
 */
export type MarineAreaCode = "AM" | "AN" | "GM" | "LC" | "LE" | "LH" | "LM" | "LO" | "LS" | "PH" | "PK" | "PM" | "PS" | "PZ" | "SL";
export declare const MarineAreaCode: {
    readonly Am: "AM";
    readonly An: "AN";
    readonly Gm: "GM";
    readonly Lc: "LC";
    readonly Le: "LE";
    readonly Lh: "LH";
    readonly Lm: "LM";
    readonly Lo: "LO";
    readonly Ls: "LS";
    readonly Ph: "PH";
    readonly Pk: "PK";
    readonly Pm: "PM";
    readonly Ps: "PS";
    readonly Pz: "PZ";
    readonly Sl: "SL";
};
