"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetarSkyCoverage = void 0;
exports.MetarSkyCoverage = {
    Ovc: "OVC",
    Bkn: "BKN",
    Sct: "SCT",
    Few: "FEW",
    Skc: "SKC",
    Clr: "CLR",
    Vv: "VV",
};
