/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MetarSkyCoverage = "OVC" | "BKN" | "SCT" | "FEW" | "SKC" | "CLR" | "VV";
export declare const MetarSkyCoverage: {
    readonly Ovc: "OVC";
    readonly Bkn: "BKN";
    readonly Sct: "SCT";
    readonly Few: "FEW";
    readonly Skc: "SKC";
    readonly Clr: "CLR";
    readonly Vv: "VV";
};
