"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetarPhenomenonIntensity = void 0;
exports.MetarPhenomenonIntensity = {
    Light: "light",
    Heavy: "heavy",
};
