"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NwsCenterWeatherServiceUnitId = void 0;
exports.NwsCenterWeatherServiceUnitId = {
    Zab: "ZAB",
    Zan: "ZAN",
    Zau: "ZAU",
    Zbw: "ZBW",
    Zdc: "ZDC",
    Zdv: "ZDV",
    Zfa: "ZFA",
    Zfw: "ZFW",
    Zhu: "ZHU",
    Zid: "ZID",
    Zjx: "ZJX",
    Zkc: "ZKC",
    Zla: "ZLA",
    Zlc: "ZLC",
    Zma: "ZMA",
    Zme: "ZME",
    Zmp: "ZMP",
    Zny: "ZNY",
    Zoa: "ZOA",
    Zob: "ZOB",
    Zse: "ZSE",
    Ztl: "ZTL",
};
