/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Three-letter identifier for a Center Weather Service Unit (CWSU).
 */
export type NwsCenterWeatherServiceUnitId = "ZAB" | "ZAN" | "ZAU" | "ZBW" | "ZDC" | "ZDV" | "ZFA" | "ZFW" | "ZHU" | "ZID" | "ZJX" | "ZKC" | "ZLA" | "ZLC" | "ZMA" | "ZME" | "ZMP" | "ZNY" | "ZOA" | "ZOB" | "ZSE" | "ZTL";
export declare const NwsCenterWeatherServiceUnitId: {
    readonly Zab: "ZAB";
    readonly Zan: "ZAN";
    readonly Zau: "ZAU";
    readonly Zbw: "ZBW";
    readonly Zdc: "ZDC";
    readonly Zdv: "ZDV";
    readonly Zfa: "ZFA";
    readonly Zfw: "ZFW";
    readonly Zhu: "ZHU";
    readonly Zid: "ZID";
    readonly Zjx: "ZJX";
    readonly Zkc: "ZKC";
    readonly Zla: "ZLA";
    readonly Zlc: "ZLC";
    readonly Zma: "ZMA";
    readonly Zme: "ZME";
    readonly Zmp: "ZMP";
    readonly Zny: "ZNY";
    readonly Zoa: "ZOA";
    readonly Zob: "ZOB";
    readonly Zse: "ZSE";
    readonly Ztl: "ZTL";
};
