/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export type NwsOfficeId = AbvthecityWeatherGov.NwsForecastOfficeId | AbvthecityWeatherGov.NwsRegionalHqId | AbvthecityWeatherGov.NwsNationalHqId;
