"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NwsRegionalHqId = void 0;
exports.NwsRegionalHqId = {
    Arh: "ARH",
    Crh: "CRH",
    Erh: "ERH",
    Prh: "PRH",
    Srh: "SRH",
    Wrh: "WRH",
};
