/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type NwsZoneType = "land" | "marine" | "forecast" | "public" | "coastal" | "offshore" | "fire" | "county";
export declare const NwsZoneType: {
    readonly Land: "land";
    readonly Marine: "marine";
    readonly Forecast: "forecast";
    readonly Public: "public";
    readonly Coastal: "coastal";
    readonly Offshore: "offshore";
    readonly Fire: "fire";
    readonly County: "county";
};
