"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NwsZoneType = void 0;
exports.NwsZoneType = {
    Land: "land",
    Marine: "marine",
    Forecast: "forecast",
    Public: "public",
    Coastal: "coastal",
    Offshore: "offshore",
    Fire: "fire",
    County: "county",
};
