/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface ObservationStationCollectionJsonLd {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    "@graph"?: AbvthecityWeatherGov.ObservationStation[];
    observationStations?: string[];
    pagination?: AbvthecityWeatherGov.PaginationInfo;
}
