/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface OfficeHeadlineCollection {
    "@context": AbvthecityWeatherGov.JsonLdContext;
    "@graph": AbvthecityWeatherGov.OfficeHeadline[];
}
