"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.QuantitativeValueQualityControl = void 0;
exports.QuantitativeValueQualityControl = {
    Z: "Z",
    C: "C",
    S: "S",
    V: "V",
    X: "X",
    Q: "Q",
    G: "G",
    B: "B",
    T: "T",
};
