"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SatelliteThumbnailsRequestArea = void 0;
exports.SatelliteThumbnailsRequestArea = {
    A: "a",
    E: "e",
    G: "g",
    H: "h",
    P: "p",
    S: "s",
    W: "w",
};
