/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface SigmetCollectionGeoJson {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    features?: AbvthecityWeatherGov.SigmetGeoJson[];
    type: "FeatureCollection";
}
