/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * An object representing a zone area forecast.
 */
export interface ZoneForecast {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    geometry?: AbvthecityWeatherGov.GeometryString | undefined;
    /** An array of forecast periods. */
    periods?: AbvthecityWeatherGov.ZoneForecastPeriodsItem[];
    /** The time this zone forecast product was published. */
    updated?: string;
    /** An API link to the zone this forecast is for. */
    zone?: string;
}
