/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface Zone {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    "@id"?: string;
    "@type"?: "wx:Zone";
    awipsLocationIdentifier?: string;
    cwa?: AbvthecityWeatherGov.NwsForecastOfficeId[];
    effectiveDate?: string;
    expirationDate?: string;
    forecastOffice?: string;
    forecastOffices?: string[];
    geometry?: AbvthecityWeatherGov.GeometryString | undefined;
    gridIdentifier?: string;
    id?: AbvthecityWeatherGov.NwsZoneId;
    name?: string;
    observationStations?: string[];
    radarStation?: string;
    state?: AbvthecityWeatherGov.ZoneState;
    timeZone?: string[];
    type?: AbvthecityWeatherGov.NwsZoneType;
}
