/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ZoneForecastPeriodsItem {
    /** A detailed textual forecast for the period. */
    detailedForecast: string;
    /** A textual description of the period. */
    name: string;
    /** A sequential identifier number. */
    number: number;
}
