/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface ZoneCollectionJsonLd {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    "@graph"?: AbvthecityWeatherGov.Zone[];
}
