/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../../index";
/**
 * @example
 *     {}
 */
export interface AlertsQueryRequest {
    /**
     * List only active alerts (use /alerts/active endpoints instead)
     */
    active?: boolean;
    /**
     * State/territory code or marine area code
     * This parameter is incompatible with the following parameters: point, region, region_type, zone
     */
    area?: AbvthecityWeatherGov.AreaCode | AbvthecityWeatherGov.AreaCode[];
    /**
     * Certainty (observed, likely, possible, unlikely, unknown)
     */
    certainty?: AbvthecityWeatherGov.AlertCertainty | AbvthecityWeatherGov.AlertCertainty[];
    /**
     * Event code
     */
    code?: string | string[];
    /**
     * Pagination cursor
     */
    cursor?: string;
    /**
     * End time
     */
    end?: string;
    /**
     * Event name
     */
    event?: string | string[];
    /**
     * Limit
     */
    limit?: number;
    /**
     * Message type (alert, update, cancel)
     */
    message_type?: AbvthecityWeatherGov.AlertsQueryRequestMessageTypeItem | AbvthecityWeatherGov.AlertsQueryRequestMessageTypeItem[];
    /**
     * Point (latitude,longitude)
     * This parameter is incompatible with the following parameters: area, region, region_type, zone
     */
    point?: AbvthecityWeatherGov.PointString;
    /**
     * Marine region code
     * This parameter is incompatible with the following parameters: area, point, region_type, zone
     */
    region?: AbvthecityWeatherGov.MarineRegionCode | AbvthecityWeatherGov.MarineRegionCode[];
    /**
     * Region type (land or marine)
     * This parameter is incompatible with the following parameters: area, point, region, zone
     */
    region_type?: AbvthecityWeatherGov.AlertsQueryRequestRegionType;
    /**
     * Severity (extreme, severe, moderate, minor, unknown)
     */
    severity?: AbvthecityWeatherGov.AlertSeverity | AbvthecityWeatherGov.AlertSeverity[];
    /**
     * Start time
     */
    start?: string;
    /**
     * Status (actual, exercise, system, test, draft)
     */
    status?: AbvthecityWeatherGov.AlertsQueryRequestStatusItem | AbvthecityWeatherGov.AlertsQueryRequestStatusItem[];
    /**
     * Urgency (immediate, expected, future, past, unknown)
     */
    urgency?: AbvthecityWeatherGov.AlertUrgency | AbvthecityWeatherGov.AlertUrgency[];
    /**
     * Zone ID (forecast or county)
     * This parameter is incompatible with the following parameters: area, point, region, region_type
     */
    zone?: AbvthecityWeatherGov.NwsZoneId | AbvthecityWeatherGov.NwsZoneId[];
}
