/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../../index";
export interface IconsDualConditionRequest {
    /**
     * Font size
     */
    fontsize?: number;
    /**
     * Font size
     */
    size?: AbvthecityWeatherGov.IconsDualConditionRequestSize;
}
