/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface RadarStationsRequest {
    /**
     * Show latency info from specific LDM host
     */
    host?: string;
    /**
     * Show RDA and latency info from specific reporting host
     */
    reportingHost?: string;
    /**
     * Limit results to a specific station type or types
     */
    stationType?: string | string[];
}
