/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface RadarServersRequest {
    /**
     * Show records from specific reporting host
     */
    reportingHost?: string;
}
