/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../../index";
/**
 * @example
 *     {}
 */
export interface AlertsActiveRequest {
    /**
     * State/territory code or marine area code
     * This parameter is incompatible with the following parameters: point, region, region_type, zone
     */
    area?: AbvthecityWeatherGov.AreaCode | AbvthecityWeatherGov.AreaCode[];
    /**
     * Certainty (observed, likely, possible, unlikely, unknown)
     */
    certainty?: AbvthecityWeatherGov.AlertCertainty | AbvthecityWeatherGov.AlertCertainty[];
    /**
     * Event code
     */
    code?: string | string[];
    /**
     * Event name
     */
    event?: string | string[];
    /**
     * Limit
     */
    limit?: number;
    /**
     * Message type (alert, update, cancel)
     */
    message_type?: AbvthecityWeatherGov.AlertsActiveRequestMessageTypeItem | AbvthecityWeatherGov.AlertsActiveRequestMessageTypeItem[];
    /**
     * Point (latitude,longitude)
     * This parameter is incompatible with the following parameters: area, region, region_type, zone
     */
    point?: AbvthecityWeatherGov.PointString;
    /**
     * Marine region code
     * This parameter is incompatible with the following parameters: area, point, region_type, zone
     */
    region?: AbvthecityWeatherGov.MarineRegionCode | AbvthecityWeatherGov.MarineRegionCode[];
    /**
     * Region type (land or marine)
     * This parameter is incompatible with the following parameters: area, point, region, zone
     */
    region_type?: AbvthecityWeatherGov.AlertsActiveRequestRegionType;
    /**
     * Severity (extreme, severe, moderate, minor, unknown)
     */
    severity?: AbvthecityWeatherGov.AlertSeverity | AbvthecityWeatherGov.AlertSeverity[];
    /**
     * Status (actual, exercise, system, test, draft)
     */
    status?: AbvthecityWeatherGov.AlertsActiveRequestStatusItem | AbvthecityWeatherGov.AlertsActiveRequestStatusItem[];
    /**
     * Urgency (immediate, expected, future, past, unknown)
     */
    urgency?: AbvthecityWeatherGov.AlertUrgency | AbvthecityWeatherGov.AlertUrgency[];
    /**
     * Zone ID (forecast or county)
     * This parameter is incompatible with the following parameters: area, point, region, region_type
     */
    zone?: AbvthecityWeatherGov.NwsZoneId | AbvthecityWeatherGov.NwsZoneId[];
}
