/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface ProductsQueryRequest {
    /**
     * End time
     */
    end?: string;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Location id
     */
    location?: string | string[];
    /**
     * Issuing office
     */
    office?: string | string[];
    /**
     * Start time
     */
    start?: string;
    /**
     * Product code
     */
    type?: string | string[];
    /**
     * WMO id code
     */
    wmoid?: string | string[];
}
