/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../../index";
/**
 * @example
 *     {}
 */
export interface SigmetQueryRequest {
    /**
     * ATSU identifier
     */
    atsu?: AbvthecityWeatherGov.AtsuIdentifier;
    /**
     * Date (YYYY-MM-DD format)
     */
    date?: AbvthecityWeatherGov.Date_;
    /**
     * End time
     */
    end?: string;
    /**
     * SIGMET sequence number
     */
    sequence?: AbvthecityWeatherGov.SigmetSequenceNumber;
    /**
     * Start time
     */
    start?: string;
}
