/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface StationObservationListRequest {
    /**
     * End time
     */
    end?: string;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Start time
     */
    start?: string;
}
