/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../../index";
/**
 * @example
 *     {}
 */
export interface ZoneListTypeRequest {
    /**
     * State/marine area code
     */
    area?: AbvthecityWeatherGov.AreaCode | AbvthecityWeatherGov.AreaCode[];
    /**
     * Effective date/time
     */
    effective?: string;
    /**
     * Zone ID (forecast or county)
     */
    id?: AbvthecityWeatherGov.NwsZoneId | AbvthecityWeatherGov.NwsZoneId[];
    /**
     * Include geometry in results (true/false)
     */
    include_geometry?: boolean;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Point (latitude,longitude)
     */
    point?: AbvthecityWeatherGov.PointString;
    /**
     * Region code
     */
    region?: AbvthecityWeatherGov.RegionCode | AbvthecityWeatherGov.RegionCode[];
    /**
     * Zone type
     */
    type?: AbvthecityWeatherGov.NwsZoneType | AbvthecityWeatherGov.NwsZoneType[];
}
