/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../../index";

/**
 * @example
 *     {}
 */
export interface AlertsQueryRequest {
    /**
     * List only active alerts (use /alerts/active endpoints instead)
     */
    active?: boolean;
    /**
     * State/territory code or marine area code
     * This parameter is incompatible with the following parameters: point, region, region_type, zone
     */
    area?: WeatherGov.AreaCode | WeatherGov.AreaCode[];
    /**
     * Certainty (observed, likely, possible, unlikely, unknown)
     */
    certainty?: WeatherGov.AlertCertainty | WeatherGov.AlertCertainty[];
    /**
     * Event code
     */
    code?: string | string[];
    /**
     * Pagination cursor
     */
    cursor?: string;
    /**
     * End time
     */
    end?: string;
    /**
     * Event name
     */
    event?: string | string[];
    /**
     * Limit
     */
    limit?: number;
    /**
     * Message type (alert, update, cancel)
     */
    message_type?: WeatherGov.AlertsQueryRequestMessageTypeItem | WeatherGov.AlertsQueryRequestMessageTypeItem[];
    /**
     * Point (latitude,longitude)
     * This parameter is incompatible with the following parameters: area, region, region_type, zone
     */
    point?: WeatherGov.PointString;
    /**
     * Marine region code
     * This parameter is incompatible with the following parameters: area, point, region_type, zone
     */
    region?: WeatherGov.MarineRegionCode | WeatherGov.MarineRegionCode[];
    /**
     * Region type (land or marine)
     * This parameter is incompatible with the following parameters: area, point, region, zone
     */
    region_type?: WeatherGov.AlertsQueryRequestRegionType;
    /**
     * Severity (extreme, severe, moderate, minor, unknown)
     */
    severity?: WeatherGov.AlertSeverity | WeatherGov.AlertSeverity[];
    /**
     * Start time
     */
    start?: string;
    /**
     * Status (actual, exercise, system, test, draft)
     */
    status?: WeatherGov.AlertsQueryRequestStatusItem | WeatherGov.AlertsQueryRequestStatusItem[];
    /**
     * Urgency (immediate, expected, future, past, unknown)
     */
    urgency?: WeatherGov.AlertUrgency | WeatherGov.AlertUrgency[];
    /**
     * Zone ID (forecast or county)
     * This parameter is incompatible with the following parameters: area, point, region, region_type
     */
    zone?: WeatherGov.NwsZoneId | WeatherGov.NwsZoneId[];
}
