/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../../index";

/**
 * @example
 *     {}
 */
export interface GridpointForecastRequest {
    /**
     * Use US customary or SI (metric) units in textual output
     */
    units?: WeatherGov.GridpointForecastUnits;
    /**
     * Enable future and experimental features (see documentation for more info):
     * * forecast_temperature_qv: Represent temperature as QuantitativeValue
     * * forecast_wind_speed_qv: Represent wind speed as QuantitativeValue
     */
    "Feature-Flags"?: WeatherGov.GridpointForecastRequestFeatureFlagsItem[];
}
