/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GridpointStationsRequest {
    /**
     * Pagination cursor
     */
    cursor?: string;
    /**
     * Limit
     */
    limit?: number;
}
