/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../../index";

/**
 * @example
 *     {
 *         interval: "P2DT12H",
 *         time: "P1Y2M10DT2H30M/2008-05-11T15:30:00Z"
 *     }
 */
export interface RadarProfilerRequest {
    /**
     * Averaging interval
     */
    interval?: WeatherGov.Iso8601Duration;
    /**
     * Time interval
     */
    time?: WeatherGov.Iso8601Interval;
}
