/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../../index";

/**
 * @example
 *     {}
 */
export interface SigmetQueryRequest {
    /**
     * ATSU identifier
     */
    atsu?: WeatherGov.AtsuIdentifier;
    /**
     * Date (YYYY-MM-DD format)
     */
    date?: WeatherGov.Date_;
    /**
     * End time
     */
    end?: string;
    /**
     * SIGMET sequence number
     */
    sequence?: WeatherGov.SigmetSequenceNumber;
    /**
     * Start time
     */
    start?: string;
}
