/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ZoneObsRequest {
    /**
     * End date/time
     */
    end?: string;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Start date/time
     */
    start?: string;
}
