/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as WeatherGov from "../../index";

/**
 * @example
 *     {}
 */
export interface ZoneListRequest {
    /**
     * State/marine area code
     */
    area?: WeatherGov.AreaCode | WeatherGov.AreaCode[];
    /**
     * Effective date/time
     */
    effective?: string;
    /**
     * Zone ID (forecast or county)
     */
    id?: WeatherGov.NwsZoneId | WeatherGov.NwsZoneId[];
    /**
     * Include geometry in results (true/false)
     */
    include_geometry?: boolean;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Point (latitude,longitude)
     */
    point?: WeatherGov.PointString;
    /**
     * Region code
     */
    region?: WeatherGov.RegionCode | WeatherGov.RegionCode[];
    /**
     * Zone type
     */
    type?: WeatherGov.NwsZoneType | WeatherGov.NwsZoneType[];
}
