"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AbvthecityWeatherGovTimeoutError = void 0;
class AbvthecityWeatherGovTimeoutError extends Error {
    constructor(message) {
        super(message);
        Object.setPrototypeOf(this, AbvthecityWeatherGovTimeoutError.prototype);
    }
}
exports.AbvthecityWeatherGovTimeoutError = AbvthecityWeatherGovTimeoutError;
