/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * An alert feed in Atom format
 */
export interface AlertAtomFeed {
    author?: AbvthecityWeatherGov.AlertAtomFeedAuthor;
    entry?: AbvthecityWeatherGov.AlertAtomEntry[];
    generator?: string;
    id?: string;
    title?: string;
    updated?: string;
}
