/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const AlertResponse = {
    Shelter: "Shelter",
    Evacuate: "Evacuate",
    Prepare: "Prepare",
    Execute: "Execute",
    Avoid: "Avoid",
    Monitor: "Monitor",
    Assess: "Assess",
    AllClear: "AllClear",
    None: "None",
};
