/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AlertsActiveRequestRegionType = "land" | "marine";
export declare const AlertsActiveRequestRegionType: {
    readonly Land: "land";
    readonly Marine: "marine";
};
