/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The code denoting the category of the subject event of the alert message.
 */
export type AlertCategory = "Met" | "Geo" | "Safety" | "Security" | "Rescue" | "Fire" | "Health" | "Env" | "Transport" | "Infra" | "CBRNE" | "Other";
export declare const AlertCategory: {
    readonly Met: "Met";
    readonly Geo: "Geo";
    readonly Safety: "Safety";
    readonly Security: "Security";
    readonly Rescue: "Rescue";
    readonly Fire: "Fire";
    readonly Health: "Health";
    readonly Env: "Env";
    readonly Transport: "Transport";
    readonly Infra: "Infra";
    readonly Cbrne: "CBRNE";
    readonly Other: "Other";
};
