/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const AlertMessageType = {
    Alert: "Alert",
    Update: "Update",
    Cancel: "Cancel",
    Ack: "Ack",
    Error: "Error",
};
