/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AlertStatus = "Actual" | "Exercise" | "System" | "Test" | "Draft";
export declare const AlertStatus: {
    readonly Actual: "Actual";
    readonly Exercise: "Exercise";
    readonly System: "System";
    readonly Test: "Test";
    readonly Draft: "Draft";
};
