/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const AlertsActiveRequestStatusItem = {
    Actual: "actual",
    Exercise: "exercise",
    System: "system",
    Test: "test",
    Draft: "draft",
};
