/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface AlertCollectionJsonLd extends AbvthecityWeatherGov.AlertCollection {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    "@graph"?: AbvthecityWeatherGov.Alert[];
}
