/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const AlertStatus = {
    Actual: "Actual",
    Exercise: "Exercise",
    System: "System",
    Test: "Test",
    Draft: "Draft",
};
