/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const AlertCertainty = {
    Observed: "Observed",
    Likely: "Likely",
    Possible: "Possible",
    Unlikely: "Unlikely",
    Unknown: "Unknown",
};
