/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * State/territory codes and marine area codes
 */
export type AreaCode = AbvthecityWeatherGov.StateTerritoryCode | AbvthecityWeatherGov.MarineAreaCode;
