/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface CenterWeatherAdvisory {
    cwsu?: AbvthecityWeatherGov.NwsCenterWeatherServiceUnitId;
    end?: string;
    id?: string;
    issueTime?: string;
    observedProperty?: string;
    sequence?: number;
    start?: string;
    text?: string;
}
