/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * A GeoJSON geometry object. Please refer to IETF RFC 7946 for information on the GeoJSON format.
 */
export type GeoJsonGeometry = AbvthecityWeatherGov.GeoJsonGeometry.LineString | AbvthecityWeatherGov.GeoJsonGeometry.MultiLineString | AbvthecityWeatherGov.GeoJsonGeometry.MultiPoint | AbvthecityWeatherGov.GeoJsonGeometry.MultiPolygon | AbvthecityWeatherGov.GeoJsonGeometry.Point | AbvthecityWeatherGov.GeoJsonGeometry.Polygon;
export declare namespace GeoJsonGeometry {
    interface LineString extends AbvthecityWeatherGov.GeoJsonGeometryLineString {
        type: "LineString";
    }
    interface MultiLineString extends AbvthecityWeatherGov.GeoJsonGeometryMultiLineString {
        type: "MultiLineString";
    }
    interface MultiPoint extends AbvthecityWeatherGov.GeoJsonGeometryMultiPoint {
        type: "MultiPoint";
    }
    interface MultiPolygon extends AbvthecityWeatherGov.GeoJsonGeometryMultiPolygon {
        type: "MultiPolygon";
    }
    interface Point extends AbvthecityWeatherGov.GeoJsonGeometryPoint {
        type: "Point";
    }
    interface Polygon extends AbvthecityWeatherGov.GeoJsonGeometryPolygon {
        type: "Polygon";
    }
}
