/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * Raw forecast data for a 2.5km grid square.
 * This is a list of all potential data layers that may appear. Some layers may not be present in all areas.
 *
 * - temperature
 * - dewpoint
 * - maxTemperature
 * - minTemperature
 * - relativeHumidity
 * - apparentTemperature
 * - heatIndex
 * - windChill
 * - wetBulbGlobeTemperature
 * - skyCover
 * - windDirection
 * - windSpeed
 * - windGust
 * - weather
 * - hazards: Watch and advisory products in effect
 * - probabilityOfPrecipitation
 * - quantitativePrecipitation
 * - iceAccumulation
 * - snowfallAmount
 * - snowLevel
 * - ceilingHeight
 * - visibility
 * - transportWindSpeed
 * - transportWindDirection
 * - mixingHeight
 * - hainesIndex
 * - lightningActivityLevel
 * - twentyFootWindSpeed
 * - twentyFootWindDirection
 * - waveHeight
 * - wavePeriod
 * - waveDirection
 * - primarySwellHeight
 * - primarySwellDirection
 * - secondarySwellHeight
 * - secondarySwellDirection
 * - wavePeriod2
 * - windWaveHeight
 * - dispersionIndex
 * - pressure: Barometric pressure
 * - probabilityOfTropicalStormWinds
 * - probabilityOfHurricaneWinds
 * - potentialOf15mphWinds
 * - potentialOf25mphWinds
 * - potentialOf35mphWinds
 * - potentialOf45mphWinds
 * - potentialOf20mphWindGusts
 * - potentialOf30mphWindGusts
 * - potentialOf40mphWindGusts
 * - potentialOf50mphWindGusts
 * - potentialOf60mphWindGusts
 * - grasslandFireDangerIndex
 * - probabilityOfThunder
 * - davisStabilityIndex
 * - atmosphericDispersionIndex
 * - lowVisibilityOccurrenceRiskIndex
 * - stability
 * - redFlagThreatIndex
 */
export interface Gridpoint {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    "@id"?: string;
    "@type"?: "wx:Gridpoint";
    elevation?: AbvthecityWeatherGov.QuantitativeValue;
    forecastOffice?: string;
    geometry?: AbvthecityWeatherGov.GeometryString | undefined;
    gridId?: string;
    gridX?: number;
    gridY?: number;
    hazards?: AbvthecityWeatherGov.GridpointHazards;
    updateTime?: string;
    validTimes?: AbvthecityWeatherGov.Iso8601Interval;
    weather?: AbvthecityWeatherGov.GridpointWeather;
}
