/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type GridpointForecastRequestFeatureFlagsItem = "forecast_temperature_qv" | "forecast_wind_speed_qv";
export declare const GridpointForecastRequestFeatureFlagsItem: {
    readonly ForecastTemperatureQv: "forecast_temperature_qv";
    readonly ForecastWindSpeedQv: "forecast_wind_speed_qv";
};
