/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Denotes the units used in the textual portions of the forecast.
 */
export type GridpointForecastUnits = "us" | "si";
export declare const GridpointForecastUnits: {
    readonly Us: "us";
    readonly Si: "si";
};
