/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type GridpointWeatherValuesItemValueItemAttributesItem = "damaging_wind" | "dry_thunderstorms" | "flooding" | "gusty_wind" | "heavy_rain" | "large_hail" | "small_hail" | "tornadoes";
export declare const GridpointWeatherValuesItemValueItemAttributesItem: {
    readonly DamagingWind: "damaging_wind";
    readonly DryThunderstorms: "dry_thunderstorms";
    readonly Flooding: "flooding";
    readonly GustyWind: "gusty_wind";
    readonly HeavyRain: "heavy_rain";
    readonly LargeHail: "large_hail";
    readonly SmallHail: "small_hail";
    readonly Tornadoes: "tornadoes";
};
