/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const GridpointForecastHourlyRequestFeatureFlagsItem = {
    ForecastTemperatureQv: "forecast_temperature_qv",
    ForecastWindSpeedQv: "forecast_wind_speed_qv",
};
