/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const GridpointWeatherValuesItemValueItemIntensity = {
    VeryLight: "very_light",
    Light: "light",
    Moderate: "moderate",
    Heavy: "heavy",
};
