/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The prevailing direction of the wind for the period, using a 16-point compass.
 */
export type GridpointForecastPeriodWindDirection = "N" | "NNE" | "NE" | "ENE" | "E" | "ESE" | "SE" | "SSE" | "S" | "SSW" | "SW" | "WSW" | "W" | "WNW" | "NW" | "NNW";
export declare const GridpointForecastPeriodWindDirection: {
    readonly N: "N";
    readonly Nne: "NNE";
    readonly Ne: "NE";
    readonly Ene: "ENE";
    readonly E: "E";
    readonly Ese: "ESE";
    readonly Se: "SE";
    readonly Sse: "SSE";
    readonly S: "S";
    readonly Ssw: "SSW";
    readonly Sw: "SW";
    readonly Wsw: "WSW";
    readonly W: "W";
    readonly Wnw: "WNW";
    readonly Nw: "NW";
    readonly Nnw: "NNW";
};
