/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type IconsDualConditionRequestSize = "small" | "medium" | "large";
export declare const IconsDualConditionRequestSize: {
    readonly Small: "small";
    readonly Medium: "medium";
    readonly Large: "large";
};
