/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const MarineAreaCode = {
    Am: "AM",
    An: "AN",
    Gm: "GM",
    Lc: "LC",
    Le: "LE",
    Lh: "LH",
    Lm: "LM",
    Lo: "LO",
    Ls: "LS",
    Ph: "PH",
    Pk: "PK",
    Pm: "PM",
    Ps: "PS",
    Pz: "PZ",
    Sl: "SL",
};
