/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const MetarPhenomenonModifier = {
    Patches: "patches",
    Blowing: "blowing",
    LowDrifting: "low_drifting",
    Freezing: "freezing",
    Shallow: "shallow",
    Partial: "partial",
    Showers: "showers",
};
