/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MetarPhenomenonWeather = "fog_mist" | "dust_storm" | "dust" | "drizzle" | "funnel_cloud" | "fog" | "smoke" | "hail" | "snow_pellets" | "haze" | "ice_crystals" | "ice_pellets" | "dust_whirls" | "spray" | "rain" | "sand" | "snow_grains" | "snow" | "squalls" | "sand_storm" | "thunderstorms" | "unknown" | "volcanic_ash";
export declare const MetarPhenomenonWeather: {
    readonly FogMist: "fog_mist";
    readonly DustStorm: "dust_storm";
    readonly Dust: "dust";
    readonly Drizzle: "drizzle";
    readonly FunnelCloud: "funnel_cloud";
    readonly Fog: "fog";
    readonly Smoke: "smoke";
    readonly Hail: "hail";
    readonly SnowPellets: "snow_pellets";
    readonly Haze: "haze";
    readonly IceCrystals: "ice_crystals";
    readonly IcePellets: "ice_pellets";
    readonly DustWhirls: "dust_whirls";
    readonly Spray: "spray";
    readonly Rain: "rain";
    readonly Sand: "sand";
    readonly SnowGrains: "snow_grains";
    readonly Snow: "snow";
    readonly Squalls: "squalls";
    readonly SandStorm: "sand_storm";
    readonly Thunderstorms: "thunderstorms";
    readonly Unknown: "unknown";
    readonly VolcanicAsh: "volcanic_ash";
};
