/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const MetarSkyCoverage = {
    Ovc: "OVC",
    Bkn: "BKN",
    Sct: "SCT",
    Few: "FEW",
    Skc: "SKC",
    Clr: "CLR",
    Vv: "VV",
};
