/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MetarPhenomenonIntensity = "light" | "heavy";
export declare const MetarPhenomenonIntensity: {
    readonly Light: "light";
    readonly Heavy: "heavy";
};
