/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
/**
 * An object representing a decoded METAR phenomenon string.
 */
export interface MetarPhenomenon {
    intensity?: AbvthecityWeatherGov.MetarPhenomenonIntensity;
    inVicinity?: boolean;
    modifier?: AbvthecityWeatherGov.MetarPhenomenonModifier;
    rawString: string;
    weather: AbvthecityWeatherGov.MetarPhenomenonWeather;
}
