/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type MetarPhenomenonModifier = "patches" | "blowing" | "low_drifting" | "freezing" | "shallow" | "partial" | "showers";
export declare const MetarPhenomenonModifier: {
    readonly Patches: "patches";
    readonly Blowing: "blowing";
    readonly LowDrifting: "low_drifting";
    readonly Freezing: "freezing";
    readonly Shallow: "shallow";
    readonly Partial: "partial";
    readonly Showers: "showers";
};
