/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const NwsRegionalHqId = {
    Arh: "ARH",
    Crh: "CRH",
    Erh: "ERH",
    Prh: "PRH",
    Srh: "SRH",
    Wrh: "WRH",
};
