/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Three-letter identifier for a NWS Regional HQ.
 */
export type NwsRegionalHqId = "ARH" | "CRH" | "ERH" | "PRH" | "SRH" | "WRH";
export declare const NwsRegionalHqId: {
    readonly Arh: "ARH";
    readonly Crh: "CRH";
    readonly Erh: "ERH";
    readonly Prh: "PRH";
    readonly Srh: "SRH";
    readonly Wrh: "WRH";
};
