/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const NwsZoneType = {
    Land: "land",
    Marine: "marine",
    Forecast: "forecast",
    Public: "public",
    Coastal: "coastal",
    Offshore: "offshore",
    Fire: "fire",
    County: "county",
};
