/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface ObservationCloudLayersItem {
    amount: AbvthecityWeatherGov.MetarSkyCoverage;
    base: AbvthecityWeatherGov.QuantitativeValue;
}
