/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface Observation {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    "@id"?: string;
    "@type"?: "wx:ObservationStation";
    barometricPressure?: AbvthecityWeatherGov.QuantitativeValue;
    cloudLayers?: AbvthecityWeatherGov.ObservationCloudLayersItem[];
    dewpoint?: AbvthecityWeatherGov.QuantitativeValue;
    elevation?: AbvthecityWeatherGov.QuantitativeValue;
    geometry?: AbvthecityWeatherGov.GeometryString | undefined;
    heatIndex?: AbvthecityWeatherGov.QuantitativeValue;
    icon?: string;
    maxTemperatureLast24Hours?: AbvthecityWeatherGov.QuantitativeValue;
    minTemperatureLast24Hours?: AbvthecityWeatherGov.QuantitativeValue;
    precipitationLast3Hours?: AbvthecityWeatherGov.QuantitativeValue;
    precipitationLast6Hours?: AbvthecityWeatherGov.QuantitativeValue;
    precipitationLastHour?: AbvthecityWeatherGov.QuantitativeValue;
    presentWeather?: AbvthecityWeatherGov.MetarPhenomenon[];
    rawMessage?: string;
    relativeHumidity?: AbvthecityWeatherGov.QuantitativeValue;
    seaLevelPressure?: AbvthecityWeatherGov.QuantitativeValue;
    station?: string;
    temperature?: AbvthecityWeatherGov.QuantitativeValue;
    textDescription?: string;
    timestamp?: string;
    visibility?: AbvthecityWeatherGov.QuantitativeValue;
    windChill?: AbvthecityWeatherGov.QuantitativeValue;
    windDirection?: AbvthecityWeatherGov.QuantitativeValue;
    windGust?: AbvthecityWeatherGov.QuantitativeValue;
    windSpeed?: AbvthecityWeatherGov.QuantitativeValue;
}
