/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface OfficeHeadline {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    "@id"?: string;
    content?: string;
    id?: string;
    important?: boolean;
    issuanceTime?: string;
    link?: string;
    name?: string;
    office?: string;
    summary?: string;
    title?: string;
}
