/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface Point {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    "@id"?: string;
    "@type"?: "wx:Point";
    county?: string;
    cwa?: AbvthecityWeatherGov.NwsForecastOfficeId;
    fireWeatherZone?: string;
    forecast?: string;
    forecastGridData?: string;
    forecastHourly?: string;
    forecastOffice?: string;
    forecastZone?: string;
    geometry?: AbvthecityWeatherGov.GeometryString | undefined;
    gridId?: AbvthecityWeatherGov.NwsForecastOfficeId;
    gridX?: number;
    gridY?: number;
    observationStations?: string;
    radarStation?: string;
    relativeLocation?: AbvthecityWeatherGov.PointRelativeLocation;
    timeZone?: string;
}
