/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Detail about an error. This document conforms to RFC 7807 (Problem Details for HTTP APIs).
 */
export interface ProblemDetail {
    /** A unique identifier for the request, used for NWS debugging purposes. Please include this identifier with any correspondence to help us investigate your issue. */
    correlationId: string;
    /** A human-readable explanation specific to this occurrence of the problem. */
    detail: string;
    /** A URI reference (RFC 3986) that identifies the specific occurrence of the problem. This is only an identifier and is not necessarily a resolvable URL. */
    instance: string;
    /** The HTTP status code (RFC 7231, Section 6) generated by the origin server for this occurrence of the problem. */
    status: number;
    /** A short, human-readable summary of the problem type. */
    title: string;
    /** A URI reference (RFC 3986) that identifies the problem type. This is only an identifier and is not necessarily a resolvable URL. */
    type: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
