/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const QuantitativeValueQualityControl = {
    Z: "Z",
    C: "C",
    S: "S",
    V: "V",
    X: "X",
    Q: "Q",
    G: "G",
    B: "B",
    T: "T",
};
