/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * For values in observation records, the quality control flag from the MADIS system. The definitions of these flags can be found at https://madis.ncep.noaa.gov/madis_sfc_qc_notes.shtml
 */
export type QuantitativeValueQualityControl = "Z" | "C" | "S" | "V" | "X" | "Q" | "G" | "B" | "T";
export declare const QuantitativeValueQualityControl: {
    readonly Z: "Z";
    readonly C: "C";
    readonly S: "S";
    readonly V: "V";
    readonly X: "X";
    readonly Q: "Q";
    readonly G: "G";
    readonly B: "B";
    readonly T: "T";
};
