/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface RelativeLocation {
    bearing?: AbvthecityWeatherGov.QuantitativeValue;
    city?: string;
    distance?: AbvthecityWeatherGov.QuantitativeValue;
    state?: string;
}
