/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface RelativeLocationJsonLd extends AbvthecityWeatherGov.RelativeLocation {
    geometry?: AbvthecityWeatherGov.GeometryString | undefined;
}
