/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const SatelliteThumbnailsRequestArea = {
    A: "a",
    E: "e",
    G: "g",
    H: "h",
    P: "p",
    S: "s",
    W: "w",
};
