/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type SatelliteThumbnailsRequestArea = "a" | "e" | "g" | "h" | "p" | "s" | "w";
export declare const SatelliteThumbnailsRequestArea: {
    readonly A: "a";
    readonly E: "e";
    readonly G: "g";
    readonly H: "h";
    readonly P: "p";
    readonly S: "s";
    readonly W: "w";
};
