/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface TextProductCollection {
    "@context"?: AbvthecityWeatherGov.JsonLdContext;
    "@graph"?: AbvthecityWeatherGov.TextProduct[];
}
