/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as AbvthecityWeatherGov from "../index";
export interface ZoneCollectionGeoJsonFeaturesItem {
    properties?: AbvthecityWeatherGov.Zone;
}
